    - name: install apache on ubuntu servers
      apt:
       name: "{{package}}"
       update_cache: yes
       state: latest


    - name: enable the apache service
      service:
         name: "{{service_name}}"
         enabled: true
         state: started

    - name: copy the files from local to remote
      copy:
        src: "{{index_file}}"
        dest: "{{destination}}/{{index_file}}"
      notify: Restart Apache
