- hosts: all
  become_user: root
  become_method: sudo
  become: yes


  vars:
    package: zip
    service_name: zip

  tasks:
    - name: install zip on remote ubuntu servers
      apt:
       name: "{{package}}"
       update_cache: yes
       state: latest
      when: ansible_distribution=="ubuntu"

    - name: enable the service on ubuntu
      service:
         name: "{{service_name}}"
         enabled: true
         state: started
      when: ansible_distribution=="ubuntu"
    - name: install ntp on remote redhat servers
      yum:
       name: zip
       update_cache: yes
       state: latest
      when: ansible_distribution=="RedHat"

    - name: enable the service on redhat
      service:
         name: zip
         enabled: true
         state: started
      when: ansible_distribution=="RedHat"    
